server:
  port: 8090

config:
  base:
    endpoint: http://service-products/api/v2/products/

spring:
  application:
    name: service-client
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

